project:
  versions:
    v1:
      version: v1
      images:
      - name: authz
        version: v0.0.1 
        url: jakinyele/zbi-authz-server:v0.0.1
        port: 50051
      templates:
        keys:
        - NAMESPACE
        - AUTHZ_DEPLOYMENT
        - AUTHZ_SERVICE
        file: ./templates/project_templates_v1.tmpl
instances:
- name: zcash
  type: zcash
  versions:
    v1:
      version: v1
      images:
      - name: node 
        version: v4.3.0 
        url: electriccoinco/zcashd:v4.3.0
        port: 18232
      - name: metrics 
        version: v0.3.6 
        url: electriccoinco/zcashd_exporter:v0.3.6
        port: 9100
      templates:
        keys:
        - CONF
        - ENVOY_CONF
        - CREDENTIALS
        - DATA
        - PARAM
        - DEPLOYMENT
        - SERVICE
        - HTTP_PROXY
        file: ./templates/zcash_templates_v1.tmpl
      methods:
        addressindex: [getaddressbalance,getaddressdeltas,getaddressmempool, getaddresstxids, getaddressutxos]
        blockchain: [getbestblockhash,getblock,getblockchaininfo,getblockcount,getblockdeltas,getblockhash,getblockhashes,getblockheader,getchaintips,getdifficulty,getmempoolinfo,getrawmempool,getspentinfo,gettxout,gettxoutproof,gettxoutsetinfo,verifychain,verifytxoutproof,z_gettreestate]
        control: [getexperimentalfeatures,getinfo,getmemoryinfo,help,setlogfilter,stop]
        disclosure: [z_getpaymentdisclosure,z_validatepaymentdisclosure]
        generating: [generate,getgenerate,setgenerate]
        mining: [getblocksubsidy,getblocktemplate,getlocalsolps,getmininginfo,getnetworkhashps,getnetworksolps,prioritisetransaction,submitblock]
        network: [addnode,clearbanned,disconnectnode,getaddednodeinfo,getconnectioncount,getdeprecationinfo,getnettotals,getnetworkinfo,getpeerinfo,listbanned,ping,setban]
        rawtransactions: [createrawtransaction,decoderawtransaction,decodescript,fundrawtransaction,getrawtransaction,sendrawtransaction,signrawtransaction]
        util: [createmultisig,estimatefee,estimatepriority,validateaddress,verifymessage,z_validateaddress]
        wallet: [addmultisigaddress,backupwallet,dumpprivkey,dumpwallet,encryptwallet,getbalance,getnewaddress,getrawchangeaddress,getreceivedbyaddress,gettransaction,getunconfirmedbalance,getwalletinfo,importaddress,importprivkey,importpubkey,importwallet,keypoolrefill,listaddresses,listaddressgroupings,listlockunspent,listreceivedbyaddress,listsinceblock,listtransactions,listunspent,lockunspent,sendmany,sendtoaddress,settxfee,signmessage,z_exportkey,z_exportviewingkey,z_exportwallet,z_getbalance,z_getmigrationstatus,z_getnewaddress,z_getnotescount,z_getoperationresult,z_getoperationstatus,z_gettotalbalance,z_importkey,z_importviewingkey,z_importwallet,z_listaddresses,z_listoperationids,z_listreceivedbyaddress,z_listunspent,z_mergetoaddress,z_sendmany,z_setmigration,z_shieldcoinbase,z_viewtransaction,zcbenchmark,zcrawjoinsplit,zcrawkeygen,zcrawreceive,zcsamplejoinsplit]
- name: Light Wallet Server
  type: lwd
  versions:
    v1:
      images:
      - name: lwd
        version: v4.3.0 
        url: electriccoinco/lwd:v4.3.0
      templates:
        keys:
        - CONF
        - DEPLOYMENT
